# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0004_auto_20160817_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='Natureza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='unknown', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='naturezas',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='naturezas', to='setup_app.Natureza'),
        ),
    ]
