# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup_app', '0005_auto_20160822_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocorrencia',
            name='periodo',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
