# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Marcador', 'verbose_name_plural': 'Marcadores'},
        ),
    ]
